import { IMAGES } from "../src/constants";

export const mockChatsData = [
    {
        id: '1',
        user: {
            id: 'u1',
            name: 'Gorgina',
            surname: 'Maleta',
            profilePictureUrl: IMAGES.johnImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Hi, how are you doing?',
                datetime: new Date('2024-10-23T10:50:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: "I’m good, thanks! You?",
                datetime: new Date('2024-10-23T11:31:00'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm3',
                message: "Great! Can you send me the files?",
                datetime: new Date('2024-10-23T12:19:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm1',
                message: 'Which files are you talking about again ? Just give me a hint;',
                datetime: new Date('2024-10-23T12:32:00'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: "Tekstaq support spreadsheet for working overtime.",
                datetime: new Date('2024-10-24T11:55:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm3',
                message: "Okay I remember now, let me get back to you in a minute if you don't mind.",
                datetime: new Date('2024-10-24T12:10:00'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm1',
                message: "It's okay I don't mind, I will wait.",
                datetime: new Date('2024-10-25T21:50:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: "Hi Gorgina, I wanted to let you know that I couldn't locate the Tekstaq spreadsheet. However, I’ll reach out to my teammates tomorrow to see if anyone has access to it. I'll keep you posted on what I find. Thanks for your patience!",
                datetime: new Date('2024-10-25T22:55:00'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm3',
                message: "Thank you for the update. I appreciate you reaching out to your teammates. Just let me know if you find anything or if there's any other way I can assist in the meantime. Looking forward to hearing back from you!",
                datetime: new Date('2024-10-25T23:21:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm1',
                message: 'Great, thank you for reaching out once again, have a great week ahead of you.',
                datetime: new Date('2024-10-26T08:54:00'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: "Thank you Tokyo, have a great week to you too.",
                datetime: new Date('2024-10-26T09:31:00'),
                senderId: 'u1',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm3',
                message: "Cheers!",
                datetime: new Date('2024-10-26T10:05:12'),
                senderId: '123',
                receiverId: 'u1',
                sent: true,
                delivered: true,
                read: false,
            },
        ],
    },
    {
        id: '2',
        user: {
            id: 'u2',
            name: 'Mike',
            surname: 'Johnson',
            profilePictureUrl: IMAGES.janeImg,
            onlineStatus: false,
        },
        messages: [
            {
                id: 'm1',
                message: 'Hey, are you coming to the meeting?',
                datetime: new Date('2024-10-25T13:45:00'),
                senderId: 'u2',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Yes, I’ll be there in 10 minutes.',
                datetime: new Date('2024-10-25T13:55:00'),
                senderId: '123',
                receiverId: 'u2',
                sent: true,
                delivered: false,
                read: false,
            },
        ],
    },
    {
        id: '3',
        user: {
            id: 'u3',
            name: 'Lisa',
            surname: 'Brown',
            profilePictureUrl: IMAGES.literatureImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Can you review the document I sent you?',
                datetime: new Date('2024-10-23T10:05:00'),
                senderId: 'u3',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Sure, give me a moment.',
                datetime: new Date('2024-10-23T10:15:00'),
                senderId: '123',
                receiverId: 'u3',
                sent: true,
                delivered: true,
                read: false,
            },
        ],
    },
    {
        id: '4',
        user: {
            id: 'u4',
            name: 'Jane',
            surname: 'Smith',
            profilePictureUrl: IMAGES.physicsImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Let’s meet for lunch tomorrow.',
                datetime: new Date('2024-10-23T12:30:00'),
                senderId: '123',
                receiverId: 'u4',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Sounds good! See you at 1 PM.',
                datetime: new Date('2024-10-23T12:35:00'),
                senderId: 'u4',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
        ],
    },
    {
        id: '5',
        user: {
            id: 'u1',
            name: 'Gorgina',
            surname: "Maleta",
            profilePictureUrl: IMAGES.mathImg,
            onlineStatus: false
        },
        messages: [
            {
                id: "m1",
                message: "hi",
                datetime: new Date('2024-10-19T08:55:00'),
                senderId: "123",
                receiverId: "u1",
                sent: true,
                delivered: true,
                read: true

            },
            {
                id: "m1",
                message: "how are you",
                datetime: new Date('2024-10-20T08:55:30'),
                senderId: "u1",
                receiverId: "123",
                sent: false,
                delivered: false,
                read: false

            },
            {
                id: "m1",
                message: "Can i have the PDF that i requested yestereday? ❤️",
                datetime: new Date('2024-10-20T08:55:00'),
                senderId: "u1",
                receiverId: "123",
                sent: false,
                delivered: false,
                read: false

            }
        ]
    },
    {
        id: '6',
        user: {
            id: 'u5',
            name: 'David',
            surname: 'Lee',
            profilePictureUrl: IMAGES.googleLogo,
            onlineStatus: false,
        },
        messages: [
            {
                id: 'm1',
                message: 'Are you free for a quick call later?',
                datetime: new Date('2024-10-19T14:00:00'),
                senderId: 'u5',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'I’m available after 3 PM.',
                datetime: new Date('2024-10-19T14:10:00'),
                senderId: '123',
                receiverId: 'u5',
                sent: true,
                delivered: false,
                read: false,
            },
        ],
    },
    {
        id: '7',
        user: {
            id: 'u6',
            name: 'Sophia',
            surname: 'Williams',
            profilePictureUrl: IMAGES.mathImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Don’t forget the presentation tomorrow!',
                datetime: new Date('2024-10-19T09:45:00'),
                senderId: 'u6',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Thanks for the reminder! I’ll be ready.',
                datetime: new Date('2024-10-19T09:50:00'),
                senderId: '123',
                receiverId: 'u6',
                sent: true,
                delivered: true,
                read: true,
            },
        ],
    },
    {
        id: '8',
        user: {
            id: 'u7',
            name: 'Oliver',
            surname: 'Smith',
            profilePictureUrl: IMAGES.userPlaceholder,
            onlineStatus: false,
        },
        messages: [
            {
                id: 'm1',
                message: 'Let’s finalize the project timeline.',
                datetime: new Date('2024-10-18T16:30:00'),
                senderId: '123',
                receiverId: 'u7',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Sure, I’ll send my feedback tonight.',
                datetime: new Date('2024-10-18T16:40:00'),
                senderId: 'u7',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: false,
            },
        ],
    },
    {
        id: '9',
        user: {
            id: 'u8',
            name: 'Emily',
            surname: 'Davis',
            profilePictureUrl: IMAGES.physicsImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Can you check the budget report for me?',
                datetime: new Date('2024-10-17T11:15:00'),
                senderId: 'u8',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'I’ll take a look and get back to you later today.',
                datetime: new Date('2024-10-19T11:25:00'),
                senderId: '123',
                receiverId: 'u8',
                sent: true,
                delivered: true,
                read: true,
            },
        ],
    },
    {
        id: '10',
        user: {
            id: 'u9',
            name: 'Samuel',
            surname: 'Martinez',
            profilePictureUrl: IMAGES.johnImg,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Did you manage to finish the draft?',
                datetime: new Date('2024-09-18T18:00:00'),
                senderId: 'u9',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'Yes, I’ll send it your way in a few minutes.',
                datetime: new Date('2024-09-19T18:05:00'),
                senderId: '123',
                receiverId: 'u9',
                sent: true,
                delivered: false,
                read: false,
            },
        ],
    },

    //Duplicates ... Added for testing scrolling..... ______________________
    {
        id: '11',
        user: {
            id: 'u11',
            name: 'Feali',
            surname: 'Milanda',
            profilePictureUrl: IMAGES.userPlaceholder,
            onlineStatus: false,
        },
        messages: [
            {
                id: 'm1',
                message: 'Let’s finalize the project timeline.',
                datetime: new Date('2024-10-18T16:30:00'),
                senderId: '123',
                receiverId: 'u7',
                sent: true,
                delivered: true,
                read: false,
            },
        ],
    },
    {
        id: '12',
        user: {
            id: 'u12',
            name: 'Gorgina',
            surname: 'Gerald',
            profilePictureUrl: IMAGES.userPlaceholder,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Can you check the budget report for me?',
                datetime: new Date('2024-10-17T11:15:00'),
                senderId: 'u8',
                receiverId: '123',
                sent: true,
                delivered: true,
                read: true,
            },
            {
                id: 'm2',
                message: 'I’ll take a look and get back to you later today.',
                datetime: new Date('2024-10-17T11:25:00'),
                senderId: '123',
                receiverId: 'u8',
                sent: true,
                delivered: true,
                read: true,
            },
        ],
    },
    {
        id: '13',
        user: {
            id: 'u13',
            name: 'Saeilo',
            surname: 'Hebard',
            profilePictureUrl: IMAGES.userPlaceholder,
            onlineStatus: true,
        },
        messages: [
            {
                id: 'm1',
                message: 'Did you manage to finish the draft?',
                datetime: new Date('2024-09-14T18:00:00'),
                senderId: 'u9',
                receiverId: '123',
                sent: true,
                delivered: false,
                read: false,
            },
        ],
    },
];
