import { IMAGES } from "../src/constants";
import { StudyFeedEntry } from "../src/types/User/Feed";

export const mockStudyFeedData: StudyFeedEntry[] = [
    {
        id: "1",
        title: "Maths Grade 12 p1",
        tutorName: "Nicolas Cage",
        tutorAvatar: IMAGES.janeImg,
        date: "12 Feb 2024",
        time: "18:00",
        duration: "1h 30min",
        rsvpCount: 176,
        live: false,
        description: "This is the physics lesson I posted on the 12 feb 2024, is on the mechanics topic. I Also solved quite a few challenging problems.",
        image: IMAGES.study_1
    },
    {
        id: "2",
        title: "Chemistry Tut.",
        tutorName: "Jack Chan",
        tutorAvatar: IMAGES.johnImg,
        date: "15 Feb 2024",
        time: "17:00",
        duration: "1h 30min",
        rsvpCount: 132,
        live: true,
        description: "Dive deep into the process of cellular respiration. We'll cover glycolysis, the Krebs cycle, and the electron transport chain.",
        image: IMAGES.study_2
    },
    {
        id: "3",
        title: "Number Theory III",
        tutorName: "James Jaeger",
        tutorAvatar: IMAGES.agmedImg,
        date: "18 Feb 2024",
        time: "19:00",
        duration: "1h 30min",
        rsvpCount: 98,
        live: true,
        description: "An in-depth look at the major events, figures, and impacts of World War II. We'll analyze key battles and their global consequences.",
        image: IMAGES.study_3
    },
    {
        id: "4",
        title: "Analytical Geometry | Circles",
        tutorName: "Nicolas Cage",
        tutorAvatar: IMAGES.druboImg,
        date: "20 Feb 2024",
        time: "16:00",
        duration: "1h 30min",
        rsvpCount: 145,
        live: true,
        description: "Explore the world of organic chemistry. We'll cover nomenclature, reactions, and properties of various organic compounds.",
        image: IMAGES.study_4
    },
    {
        id: "5",
        title: "Laws of Exponents Made simple",
        tutorName: "Ian McKellen",
        tutorAvatar: IMAGES.janeImg,
        date: "22 Feb 2024",
        time: "18:30",
        duration: "1h 30min",
        rsvpCount: 87,
        live: false,
        description: "A deep dive into Shakespeare's classic tragedy. We'll analyze themes, characters, and the play's enduring impact on literature.",
        image: IMAGES.study_5
    },
    {
        id: "6",
        title: "Law 101",
        tutorName: "Stephen Hawking",
        tutorAvatar: IMAGES.janeImg,
        date: "25 Feb 2024",
        time: "19:00",
        duration: "1h 30min",
        rsvpCount: 201,
        live: false,
        description: "Explore the fascinating world of quantum mechanics. We'll cover wave-particle duality, the uncertainty principle, and quantum entanglement.",
        image: IMAGES.study_6
    },
    {
        id: "7",
        title: "Maths Grade 10 | Test Re-Visit",
        tutorName: "Frida Kahlo",
        tutorAvatar: IMAGES.johnImg,
        date: "27 Feb 2024",
        time: "17:30",
        duration: "1h 30min",
        rsvpCount: 76,
        live: false,
        description: "Journey through the Renaissance period. We'll examine key artists, their works, and the cultural context that shaped this pivotal era in art history.",
        image: IMAGES.study_7
    },
    {
        id: "8",
        title: "Law’s of Motion",
        tutorName: "Ada Lovelace",
        tutorAvatar: IMAGES.johnImg,
        date: "1 Mar 2024",
        time: "18:00",
        duration: "1h 30min",
        rsvpCount: 189,
        live: false,
        description: "Dive into the world of algorithms. We'll cover sorting algorithms, search algorithms, and analyze their time and space complexities.",
        image: IMAGES.study_8
    },
    {
        id: "9",
        title: "Number Theory III",
        tutorName: "Paul Krugman",
        tutorAvatar: IMAGES.johnImg,
        date: "3 Mar 2024",
        time: "19:30",
        duration: "1h 30min",
        rsvpCount: 112,
        live: false,
        description: "Explore key concepts in macroeconomics. We'll discuss GDP, inflation, unemployment, and monetary policy.",
        image: IMAGES.study_9
    },
    {
        id: "10",
        title: "Geological sciences exam walk through.",
        tutorName: "Sigmund Freud",
        tutorAvatar: IMAGES.druboImg,
        date: "5 Mar 2024",
        time: "17:00",
        duration: "1h 30min",
        rsvpCount: 156,
        live: false,
        description: "Delve into cognitive psychology. We'll explore perception, memory, problem-solving, and decision-making processes of the human mind.",
        image: IMAGES.study_10
    },

    {
        id: "11",
        title: "Machenical engineering Tu- W2.",
        tutorName: "Nicolas Cage",
        tutorAvatar: IMAGES.janeImg,
        date: "12 Feb 2024",
        time: "18:00",
        duration: "1h 30min",
        rsvpCount: 176,
        live: true,
        description: "This is the physics lesson I posted on the 12 feb 2024, is on the mechanics topic. I Also solved quite a few challenging problems.",
        image: IMAGES.study_11
    },
    {
        id: "12",
        title: "Accounting prev test solutions",
        tutorName: "Agmed Kubo",
        tutorAvatar: IMAGES.agmedImg,
        date: "15 Feb 2024",
        time: "17:00",
        duration: "1h 30min",
        rsvpCount: 132,
        live: false,
        description: "Dive deep into the process of cellular respiration. We'll cover glycolysis, the Krebs cycle, and the electron transport chain.",
        image: IMAGES.study_12
    },
    {
        id: "13",
        title: "Theology extra lesson.",
        tutorName: "James Jaeger",
        tutorAvatar: IMAGES.druboImg,
        date: "18 Feb 2024",
        time: "19:00",
        duration: "1h 30min",
        rsvpCount: 98,
        live: false,
        description: "An in-depth look at the major events, figures, and impacts of World War II. We'll analyze key battles and their global consequences.",
        image: IMAGES.study_13
    },
    {
        id: "14",
        title: "Mechatronics Exam Re-Visit.",
        tutorName: "Nicolas Cage",
        tutorAvatar: IMAGES.druboImg,
        date: "20 Feb 2024",
        time: "16:00",
        duration: "1h 30min",
        rsvpCount: 145,
        live: true,
        description: "Explore the world of organic chemistry. We'll cover nomenclature, reactions, and properties of various organic compounds.",
        image: IMAGES.study_14
    },
    {
        id: "15",
        title: "Passion in Design Arts.",
        tutorName: "Ian McKellen",
        tutorAvatar: IMAGES.janeImg,
        date: "22 Feb 2024",
        time: "18:30",
        duration: "1h 30min",
        rsvpCount: 87,
        live: false,
        description: "A deep dive into Shakespeare's classic tragedy. We'll analyze themes, characters, and the play's enduring impact on literature.",
        image: IMAGES.study_15
    },
    {
        id: "16",
        title: "Music theory prev test lookup.",
        tutorName: "Stephen Hawking",
        tutorAvatar: IMAGES.janeImg,
        date: "25 Feb 2024",
        time: "19:00",
        duration: "1h 30min",
        rsvpCount: 201,
        live: false,
        description: "Explore the fascinating world of quantum mechanics. We'll cover wave-particle duality, the uncertainty principle, and quantum entanglement.",
        image: IMAGES.study_16
    },
    {
        id: "17",
        title: "Language Learning Model (LLM).",
        tutorName: "Frida Kahlo",
        tutorAvatar: IMAGES.johnImg,
        date: "27 Feb 2024",
        time: "17:30",
        duration: "1h 30min",
        rsvpCount: 76,
        live: false,
        description: "Journey through the Renaissance period. We'll examine key artists, their works, and the cultural context that shaped this pivotal era in art history.",
        image: IMAGES.study_17
    },
    {
        id: "18",
        title: "Economics Week 5 Class.",
        tutorName: "Ada Lovelace",
        tutorAvatar: IMAGES.agmedImg,
        date: "1 Mar 2024",
        time: "18:00",
        duration: "1h 30min",
        rsvpCount: 189,
        live: false,
        description: "Dive into the world of algorithms. We'll cover sorting algorithms, search algorithms, and analyze their time and space complexities.",
        image: IMAGES.study_18
    }
];